### ISSUE TITLE
AudioPlayers Package failed in Xcode

### ISSUE THREAD

**Issue by rabihmb** [KarimElghamry/chillify#23]
I can't generate an archive for iOs. When I launch Archive, it stops with the following error: ../ios/Runner/GeneratedPluginRegistrant.m:6:9: 'audioplayers/AudioplayersPlugin.h' file not found

I applied the commands below

```
flutter packages get
sudo gem install cocoapods
pod repo update
pod install
```
 
 in addition, I ran the commands `brew install cocoapods`

any idea?

**Comment by KarimElghamry** [comment]
As of now, the application only works on Android as stated in the **ReadMe.md** file. The iOS version will hopefully be implemented soon, stay tuned.

if you have any further questions, please let me know.

**Comment by rabihmb** [comment]
> 
> 
> As of now, the application only works on Android as stated in the **ReadMe.md** file. The iOS version will hopefully be implemented soon, stay tuned.
> 
> if you have any further questions, please let me know.

I saw it, but I'm asking because the Packages of AudioPlayers is out of your scope and you are not handling it, in this case shall you clone it and modify the package?

**Comment by KarimElghamry** [comment]
I am still considering a couple of solutions. either write my own standalone iOS package or make a pull request to the Flute_Music_Player repo. Either way, it will take sometime before being implemented.

**Comment by tylerweitzman** [comment]
Any update since?

**Comment by KarimElghamry** [comment]
@tylerweitzman Sadly, I have been busy working on other projects lately and I haven't had a chance to work on the iOS aspect of Chillify. Also, the fact that the `flute_music_player` package is not being maintained by its creator is adding layers of obstacles, as it uses a set of deprecated APIs and requires a full rewrite of the package to support both platforms. In the meantime, if you can provide help in such matter, please consider making a pull request to the `flute_music_player` package or directly to Chillify. 


Thank you for checking out Chillify!
