### ISSUE TITLE
Where is location of music file

### ISSUE THREAD

**Issue by fibonacci998** [KarimElghamry/chillify#24]
Hi, i have tried install your app. But it cannot scan my library media. Which folder i can copy music to?

**Comment by KarimElghamry** [comment]
Hello @fibonacci998 !

thank you for trying out the app. I am using the [flute_music_player](https://pub.dev/packages/flute_music_player) package to search for music. It searches for all music files in your phone's storage by default. Note that this app is only working for Android in the meantime. 

can you give me more details so I can assist you further?

thank you.
