### ISSUE TITLE
Need online, offline support and social activity

### ISSUE THREAD

**Issue by sanjibnarzary** [KarimElghamry/chillify#25]
The music player should support
[x] User accounts
[x] Each account may manage their own songs both private or public
[x] Music suggestion based on user preference, user likes, and interest
[x] User can buy/rent or even lend their songs

**Comment by KarimElghamry** [comment]
hello @sanjibnarzary ! thank you for checking out Chillify. 

unfortunately, the features that you've mentioned are not going to be implemented in the near as it is out of the app's scope. However, If you have any more suggestions, do not hesitate to mention them here or feel free to open a new issue.

Thank you!
