### ISSUE TITLE
Restore scroll position

### ISSUE THREAD

**Issue by janwirth** [KarimElghamry/chillify#29]
First off: This is awesome! Thank you. I am using this on a Xiami Mii A2 lite.

Secondly: When I am in the albums overview and go into an album and return to the overview, I am at the top of the list. Now I have to scroll back down to where I left off.

**Comment by KarimElghamry** [comment]
Hi FranzSkuffka, Thank you for checking out Chillify!

an update will be rolled out hopefully this weekend with some bug fixes and I will for-sure include your suggestion into the update.

Thank you so much for the support and do not hesitate to contact me for any further information!

**Comment by KarimElghamry** [comment]
Hi FranzSkuffa!

I have updated Chillify with some bug fixes and improvements and included your suggestion in the update. check the latest version here: https://github.com/KarimElghamry/chillify/releases/tag/v1.5

Thank you for your feedback!
