### ISSUE TITLE
Please update versionName and versionCode

### ISSUE THREAD

**Issue by IzzySoft** [KarimElghamry/chillify#36]
Your last version (at tag v1.5) still identifies as

    package: name='com.example.music_app' versionCode='1' versionName='1.0.0' platformBuildVersionName='1.0.0' compileSdkVersion='28' compileSdkVersionCodename='9'

According to the tag name, `versionName` should be `1.5` – and `versionCode` 2 or higher. The latter is what Android uses to keep versions apart and decide whether an APK contains an update. v1.5 would never be considered an update, as it still has the lowest versionCode possible. Can you please fix that? Thanks!

**Comment by KarimElghamry** [comment]
Thank you for pointing out this issue. The version name and number were changed in #39 and the new release apk was uploaded to the [`v1.5` tag](https://github.com/KarimElghamry/chillify/releases/tag/v1.5).


if you have any other suggestions, do not hesitate to open a new issue. Thank you!

**Comment by IzzySoft** [comment]
Thanks a lot! And except for the suggestion to have tag names match versionNames (e.g. v1.5 would be v1.5.0 as versionName is 1.5.0), I currently have none :smile:

PS: update should [show up here](https://apt.izzysoft.de/fdroid/index/apk/com.example.music_app) in about half an hour (with the next sync). If you want to point out its availability there (users can fetch it with the F-Droid client to automatically receive updates), [here's a badge](https://gitlab.com/IzzyOnDroid/repo#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) you can use for that :wink: As your app seems to meet the criteria, I also gladly assist you if you want to bring it to the [F-Droid](https://f-droid.org/) main repo. Feel free to open a new issue for that and ping me from there if I shall get you started with that.
